# development:
#   host: dev.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
# staging:
#   host: staging.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
# production:
#   host: www.example.com
#   email: john@doe.net
#   password: apassword
#   # api_key: <your api key here>
hosting:
  host: pmf.locomotivehosting.com
  api_key: e903c6b15667975c10c413008acd4f1058643b78
