# Human readable name of this type
name: Produkte

# Lowercase, underscored handle used to access this type
slug: products

# Explanatory text displayed in the back-office
description: Die zu verkaufenden Produkte

# Slug of field used to identify entries by default, such as the title
label_field_name: name

# Valid values: manually, created_at, updated_at, or the slug of any field
order_by: manually

# Valid values: asc (ascending) and desc (descending). Set to asc by default.
# order_direction: asc

# Specify a field slug to group entries by that field in the back-office.
# group_by: <your field>

# Activate public 'create' API (e.g for a contact form)
# public_submission_enabled: false

# Array of emails to be notified of new entries made with the public API
# public_submission_accounts: ['john@example.com']

# A list describing each field
fields:
- name: # The lowercase, underscored name of the field
    label: Name # Human readable name of the field
    type: string
    required: true
    hint: Produktename
    localized: true
    searchable: false

- tags: # The lowercase, underscored name of the field
    label: Tags # Human readable name of the field
    type: tags
    required: true
    hint: Mit diesen Tags wird das Produkt zu gewissen Leiden zugeordnet und entsprechend verkauft.
    localized: false

- description:
    label: Anwendungsbereich
    type: text
    required: false
    hint: Kurze beschreibung der möglichen Anwendungsfälle.
    localized: false
    searchable: false

- application:
    label: Anwendungsbereich
    type: text
    required: false
    hint: Kurze beschreibung der möglichen Anwendungsfälle.
    localized: false
    searchable: false

- ingredience:
    label: Inhaltsbeschreibung
    type: text
    required: false
    hint: Kurze beschreibung der möglichen Anwendungsfälle.
    localized: false
    searchable: false

- amount:
    label: Inhalt
    type: text
    required: false
    hint: Angabe zur Inhaltsmenge.
    localized: false
    searchable: false

- picture: # The lowercase, underscored name of the field
    label: Bild # Human readable name of the field
    type: file
    required: false
    hint: "Rechteckiges Produktbild (100x100px)"
    localized: false

- url: # The lowercase, underscored name of the field
    label: Produkturl # Human readable name of the field
    type: string
    required: true
    hint: Relativer Pfad zur Produktübersicht.
    localized: false
    # text_formatting: html # html (uses rich text editor) or text (uses plain text editor)

- price:
    label: Preis
    type: float
    required: false
    hint: "Der aktuelle Preis (muss mit dem auf Snipcart hinterlegten Preis übereinstimmen)."
    localized: false
    searchable: false