source 'https://rubygems.org'

# gem 'locomotivecms_mounter', '~> 1.5.0'
# DEBUG
gem 'locomotivecms_mounter', '~> 1.5.0', path: '/Users/didier/Documents/LocomotiveCMS/gems/mounter'

gem 'twitter', '~> 5.13.0'
gem 'thor', '~> 0.19.1'
gem 'colorize', '~> 0.5.8'
gem 'rspec'
